### ISSUE TITLE
Wavelength calibration to very long slit

### ISSUE THREAD

**Issue by YuichiHarikane** [Mosfire-DataReductionPipeline/MosfireDRP#14]
I am now performing reduction to the data we obtain using MOSFIRE DRP.
But wavelength calibration does not go well in some slits which are spatially very long (~1000 pixels).

For example, if we perform
Wavelength.fit_lambda(maskname, band, obsfiles, obsfiles,waveops)
on "mask_sxds59407_v4_slit07", the result is
"rectified_wave_stack_Y_m141124_0183-0208.fits.gz"(see attached images).
Wavelength calibration in the lower very long slit looks like bad.
I think previous commands (Flatting, Wavelength fitting with night lines...)
have gone well.

Error messages appear when I do "Wavelength.fit_lambda", such as
/Users/hari/Ureka/python/lib/python2.7/site-packages/numpy/core/_methods.py:79: RuntimeWarning: Degrees of freedom <= 0 for slice
  warnings.warn("Degrees of freedom <= 0 for slice", RuntimeWarning)
/Users/hari/Ureka/python/lib/python2.7/site-packages/numpy/core/_methods.py:55: RuntimeWarning: Mean of empty slice.
  warnings.warn("Mean of empty slice.", RuntimeWarning)
.

Same bad wavelength calibration occurs in other masks such as
C37050_Y07_v2, which also has very long slit.

Do you have any idea about this?

![image1_rectified_wave_stack_y_m141124_0183-0208 fits gz](https://cloud.githubusercontent.com/assets/11048331/6260920/ea7e38dc-b829-11e4-8272-db57145a7094.png)
![image2_rectified_wave_stack_y_m141124_0183-0208 fits gz](https://cloud.githubusercontent.com/assets/11048331/6260923/ec171998-b829-11e4-8bf1-8907d9b14785.png)

**Comment by nickkonidaris** [comment]
Yuichi,

This problem has to do with the "lags" in Wavelength.py. There's a line
that looks something like:

lags = np.arange(-30,30)

you should increase this to (-50, 50). My suggested change will basically
half the speed of the DRP; however, it may solve your problem.

~ N

On Wed, Feb 18, 2015 at 6:26 PM, YuichiHarikane <notifications@github.com>
wrote:

> I am now performing reduction to the data we obtain using MOSFIRE DRP.
> But wavelength calibration does not go well in some slits which are
> spatially very long (~1000 pixels).
>
> For example, if we perform
> Wavelength.fit_lambda(maskname, band, obsfiles, obsfiles,waveops)
> on "mask_sxds59407_v4_slit07", the result is
> "rectified_wave_stack_Y_m141124_0183-0208.fits.gz"(see attached images).
> Wavelength calibration in the lower very long slit looks like bad.
> I think previous commands (Flatting, Wavelength fitting with night
> lines...)
> have gone well.
>
> Error messages appear when I do "Wavelength.fit_lambda", such as
> /Users/hari/Ureka/python/lib/python2.7/site-packages/numpy/core/_methods.py:79:
> RuntimeWarning: Degrees of freedom <= 0 for slice
> warnings.warn("Degrees of freedom <= 0 for slice", RuntimeWarning)
> /Users/hari/Ureka/python/lib/python2.7/site-packages/numpy/core/_methods.py:55:
> RuntimeWarning: Mean of empty slice.
> warnings.warn("Mean of empty slice.", RuntimeWarning)
> .
>
> Same bad wavelength calibration occurs in other masks such as
> C37050_Y07_v2, which also has very long slit.
>
> Do you have any idea about this?
>
> [image: image1_rectified_wave_stack_y_m141124_0183-0208 fits gz]
> <https://cloud.githubusercontent.com/assets/11048331/6260920/ea7e38dc-b829-11e4-8272-db57145a7094.png>
> [image: image2_rectified_wave_stack_y_m141124_0183-0208 fits gz]
> <https://cloud.githubusercontent.com/assets/11048331/6260923/ec171998-b829-11e4-8bf1-8907d9b14785.png>
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/Mosfire-DataReductionPipeline/MosfireDRP/issues/14>.
>



-- 
   +1 831 704 6425

**Comment by YuichiHarikane** [comment]
Dear Nick,

If I change the values to (-50,50), wavelength calibration goes well!
The final product (...eps.fits) is also OK.
Thank you for your advice.

Best wishes,
Yuichi Harikane.

![rectified_wave_stack_y_m141124_0183-0208](https://cloud.githubusercontent.com/assets/11048331/6268660/d5788e0c-b891-11e4-8019-4c4245c3e49e.png)
