### ISSUE TITLE
DATASEC keyword in the rectified outputs and DS9

### ISSUE THREAD

**Issue by monodera** [Mosfire-DataReductionPipeline/MosfireDRP#15]
Perhaps due to the DATASEC keyword in the FITS header of rectified outputs from MosfireDRP (this is carried over from the raw frames), DS9 only displays [1:2048,1:2048] when NAXIS1 and NAXIS2 are larger than 2048.  When I removed this keyword, DS9 properly displays the image.  This happens to me only for "[MASKNAME]_[BAND]_{eps,itime,sig,snrs}.fits" files, not for 2D spectra of individual objects. 

I guess the pipeline can either remove or rename the keyword at the rectification. 

This problem does not happen to relatively old data (in my case, those taken in Jan 2014) likely because DATASEC key does not exist in the header of raw frames. 

I'm using MosfireDRP-1.1 and DS9 7.3.2 on OS X 10.10.2.

Masato Onodera

**Comment by nickkonidaris** [comment]
Hi Masato,

You can use the code here:
https://code.google.com/p/mosfire/source/browse/MOSFIRE/IO.py

to solve your DATASEC issue. I have not tested the code from the google
code repository against what is in the github repository.

~ N

On Thu, Feb 19, 2015 at 6:26 AM, monodera <notifications@github.com> wrote:

> Perhaps due to the DATASEC keyword in the FITS header of rectified outputs
> from MosfireDRP (this is carried over from the raw frames), DS9 only
> displays [1:2048,1:2048] when NAXIS1 and NAXIS2 are larger than 2048. When
> I removed this keyword, DS9 properly displays the image. This happens to me
> only for "[MASKNAME]*[BAND]*{eps,itime,sig,snrs}.fits" files, not for 2D
> spectra of individual objects.
>
> I guess the pipeline can either remove or rename the keyword at the
> rectification.
>
> This problem does not happen to relatively old data (in my case, those
> taken in Jan 2014) likely because DATASEC key does not exist in the header
> of raw frames.
>
> I'm using MosfireDRP-1.1 and DS9 7.3.2 on OS X 10.10.2.
>
> Masato Onodera
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/Mosfire-DataReductionPipeline/MosfireDRP/issues/15>.
>



-- 
   +1 831 704 6425

**Comment by monodera** [comment]
Hi Nick, 

Thanks.  I've copied the old IO.py to the MOSFIRE directory and it worked as expected. 

Masato

**Comment by lucarizzi** [comment]
Nick,
thank you for responding to this and providing a solution.
I will compare IO.py with the current branch and include it.
Luca
