### ISSUE TITLE
Double peaked emission line: nod shift issue?

### ISSUE THREAD

**Issue by jhyoon79** [Mosfire-DataReductionPipeline/MosfireDRP#3]
I have multiple frames with the ABBA dither pattern of the nod amplitude 2".
When I reduced all frames with DRP 1.0, an emission line shows a double peak.
All the frames taken for 2 nights show the same problem.

An example 2D spectrum is attached.

Thanks

![screen shot 2015-01-05 at 4 50 37 pm](https://cloud.githubusercontent.com/assets/4965718/5622626/0ac15022-94fb-11e4-9a2e-7b2c27c57687.png)

**Comment by MosfireDRP** [comment]
Dear Joo Heon Yoon
thank you for submitting this report.

One of us will get back to you as soon as possible.
For the time being, could you verify that the YOFFSET keyword on your images are set correctly?

**Comment by jhyoon79** [comment]
Yes, it's 2. As I said, the Nod amplitude was set to be 2".

**Comment by MosfireDRP** [comment]
Could you make the corresponding data (including calibrations) available to us on a ftp server? I would be happy to try to re-reduce your data and see if I can figure out why the pipeline is not combining your data correctly.

**Comment by jhyoon79** [comment]
I have figured it out.
I looked at Rectify.py and found out that the line 77 is looking for "offset" (as shown in the attached image).
I think it needs to look for "yoffset".
Since the DRP couldn't find "offset", it was using the default shift 3.0 but my data require shift of 4.0.
When I corrected "offset" to "yoffset", the emission in the data looks fine.

Can you please check if my finding is correct? Just to make sure...

Thanks

![screen shot 2015-01-05 at 11 59 08 pm](https://cloud.githubusercontent.com/assets/4965718/5625814/fa1090d0-9536-11e4-90f2-23a28af94a78.png)

**Comment by csteidel** [comment]
This bug was introduced in the process of the (very recent) replacement of calls to "has_key" with "in" to be compatible with the latest Ureka version.  The section of code that had worked for quite some time prior to the change looks like this:


![untitled](https://cloud.githubusercontent.com/assets/9736870/5633125/29e4243c-9589-11e4-8a25-bc00d1c1e8bf.png)

**Comment by lucarizzi** [comment]
Thanks Chuck. The code is updated to remove the bug I had introduced. I also checked all the other instances of replacement of has_key().
I will update the current release
