### ISSUE TITLE
Compatible with Ureka 1.4?

### ISSUE THREAD

**Issue by anstockton** [Mosfire-DataReductionPipeline/MosfireDRP#5]
Has there been any progress with making the DRP compatible with Ureka 1.4? There was a problem reported earlier with "has_key()", which is no longer available in the current Python version. Using the "in" operator instead seems to work, but I would rather not end up doing too much personal editing of the tasks.

**Comment by MosfireDRP** [comment]
Dear Alan
yes, the current version of the pipeline does not use has_key() any more, and all the calls have been changed to the "in" operator.
If you find any leftover occurrences of the has_key() operator (the error code should be obvious), please let us know and we will change the code.
